- hosts: all
  become: yes
  gather_facts: false
  tasks:

    - name: add backports apt sources
      apt_repository: repo="deb http://http.debian.net/debian jessie-backports main" state=present

- hosts: head
  become: yes
  gather_facts: false
  tasks:

    - name: install system dependencies
      apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
      with_items:
        - apt-transport-https
        - ca-certificates
