- hosts: all
  become: yes
  gather_facts: false
  tasks:
    - include_vars: roles/ogs/defaults/main.yml
    - include: roles/ogs/tasks/common.yml

- hosts: head
  become: yes
  gather_facts: false
  roles:
    - nfs
  tasks:
    - include_vars: roles/ogs/defaults/main.yml
    - include: roles/ogs/tasks/head.yml
