- hosts: all
  become: yes
  tasks:
    - include_vars: roles/ogs/defaults/main.yml
    - include: roles/ogs/tasks/common.yml

- hosts: head
  become: yes
  gather_facts: false
  roles:
    - nfs
  tasks:
    - include_vars: roles/ogs/defaults/main.yml
    - include: roles/ogs/tasks/head.yml

- hosts: workers
  become: yes
  gather_facts: false
  tasks:
    - include_vars: roles/ogs/defaults/main.yml
    - include: roles/ogs/tasks/workers.yml

- hosts: head
  become: yes
  gather_facts: false
  tasks:
    - include_vars: roles/ogs/defaults/main.yml
    - include: roles/ogs/tasks/head_postinstall.yml

- hosts: workers
  become: yes
  gather_facts: false
  tasks:
    - include_vars: roles/ogs/defaults/main.yml
    - include: roles/ogs/tasks/workers_postinstall.yml

- hosts: all
  become: yes
  tasks:
    - include_vars: roles/ogs/defaults/main.yml
    - include: roles/ogs/tasks/common_postinstall.yml
