---

- name: add additional apt sources
  apt_repository: repo={{ item }} state=present
  with_items:
    - "deb http://httpredir.debian.org/debian wheezy main"
    - "deb-src http://httpredir.debian.org/debian wheezy main"

- name: install build dependencies
  apt: pkg={{ item }} state=present force=yes update_cache=yes cache_valid_time=3600
  with_items:
    - ant
    - apt-transport-https
    - ca-certificates
    - csh
    - build-essential
    - git
    - javacc
    - junit
    - libxext-dev
    - libxft-dev
    - libmotif-dev
    - libncurses-dev
    - libpam0g-dev
    - libreadline-dev
    - libssl-dev
    - libxp-dev
    - libxpm-dev
    - libxmu-dev
    - texinfo=4.13a.dfsg.1-10
    - openjdk-7-jdk

- name: add user group
  group:
    name={{ ogs_group }}
    gid={{ ogs_gid }}
    state=present

- name: add admin user account
  user:
    name={{ ogs_admin_user }}
    uid={{ ogs_uid }}
    group={{ ogs_group }}
    shell=/bin/bash
    state=present

- name: set sudoers template into place, after passing validation with visudo
  template:
    src: templates/sudoers
    dest: /etc/sudoers
    validate: 'visudo -cf %s'

- name: ensure user SSH directory exists
  file: path="/home/{{ ogs_admin_user }}/.ssh" state=directory owner={{ ogs_admin_user }} group={{ ogs_group }} mode=0755

- name: copy SSH private key
  copy: src="{{ ogs_admin_private_key }}" dest="/home/{{ ogs_admin_user }}/.ssh/id_rsa" owner={{ ogs_admin_user }} group={{ ogs_group }} mode=0600

- name: copy SSH public key
  copy: src="{{ ogs_admin_public_key }}" dest="/home/{{ ogs_admin_user }}/.ssh/id_rsa.pub" owner={{ ogs_admin_user }} group={{ ogs_group }} mode=0644

- name: copy SSH public key to authorized_keys
  copy: src="{{ ogs_admin_public_key }}" dest="/home/{{ ogs_admin_user }}/.ssh/authorized_keys" owner={{ ogs_admin_user }} group={{ ogs_group }} mode=0644

- name: set known hosts
  template: src=templates/known_hosts.j2 dest="/home/{{ ogs_admin_user }}/.ssh/known_hosts" owner={{ ogs_admin_user }} group={{ ogs_group }} mode=0644

- name: copy ogs.sh file
  copy:
    src=files/ogs.sh
    dest=/etc/profile.d/ogs.sh
