---

- name: copy setup configuration
  template:
    src=templates/inst_template.conf.j2
    dest=/nfs/ogs/inst_config.txt
    owner={{ ogs_admin_user }}
    group={{ ogs_group }}
    mode=0644

- name: setup sge_qmaster
  shell: ./inst_sge -m -noremote -auto ./inst_config.txt
  args:
    chdir: /nfs/ogs
    creates: "/nfs/ogs/{{ ogs_cell_name|default('default') }}/common/cluster_name"
    executable: /bin/bash
  environment:
    SGE_ROOT: /nfs/ogs
    SGE_ARCH: linux-x64
