---

- name: copy setup configuration
  template:
    src=templates/inst_template.conf.j2
    dest=/nfs/ogs/inst_config.txt
    owner={{ ogs_admin_user }}
    group={{ ogs_group }}
    mode=0644

- name: setup sge_execd
  shell: ./inst_sge -x -noremote -auto ./inst_config.txt
  args:
    chdir: /nfs/ogs
    creates: "/nfs/ogs/{{ ogs_cell_name|default('default') }}/spool/execd/{{ inventory_hostname }}"
    executable: /bin/bash
  environment:
    SGE_ROOT: /nfs/ogs
    SGE_ARCH: linux-x64

- name: register if execd is running
  stat: path=/nfs/ogs/default/spool/execd/{{ inventory_hostname }}/execd.pid
  register: execd_pid
  changed_when: False

- name: register if shadow daemon is running
  stat: path=/nfs/ogs/default/spool/master/shadowd_{{ inventory_hostname }}.pid
  register: shadowd_pid
  changed_when: False

- name: start execd and or shadow daemon if pid does not exist
  shell: /nfs/ogs/default/common/sgemaster
  when:  (execd_pid.stat.exists == False) or
         (shadowd_pid.stat.exists == False)
